# part 1


How to create an empty and a full NumPy array?

Create a Numpy array filled with all zeros

Create a Numpy array filled with all ones

Flatten a 2d numpy array into 1d array

Reverse a numpy array

Change data type of given numpy array

# part 2

Get the maximum value from given matrix

Get the minimum value from given matrix

Find the number of rows and columns of a given matrix using NumPy

Select the elements from a given matrix

Find the sum of values in a matrix

Calculate the sum of the diagonal elements of a NumPy array

Adding and Subtracting Matrices in Python

Ways to add row/columns in numpy array


In [2]:
#PART 1
#How to create an empty and a full NumPy array?

import numpy as np

empty1 = np.empty([4, 4])
print("Empty Array")
print(empty1)

full1 = np.full([4, 4],2)
print("\n Full Array")
print(full1)

Empty Array
[[5.e-324 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]
 [0.e+000 0.e+000 0.e+000 0.e+000]]

 Full Array
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [4]:
#Create a Numpy array filled with all zeros
import numpy as np
a=np.zeros([4,4], dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [5]:
#Create a Numpy array filled with all ones
import numpy as np
a=np.ones([4,4], dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [9]:
#Flatten a 2d numpy array into 1d array
import numpy as np
arr=np.array([[0,1,2],[3,4,5],[5,6,7],[7,8,9]])
print(arr)

flt=arr.flatten()
print(flt)

[[0 1 2]
 [3 4 5]
 [5 6 7]
 [7 8 9]]
[0 1 2 3 4 5 5 6 7 7 8 9]


In [10]:
#Reverse a numpy array
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
res = np.flip(arr)
print(res)


[5 4 6 3 2 1]


In [11]:
#Change data type of given numpy array
import numpy as np
a = np.array([1.9, 1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1])
print(a.dtype)
a = a.astype(np.int32)
print(a.dtype)

float64
int32


In [14]:
#PART 2
#Get the maximum value from given matrix
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
res=np.max(arr)
print(res)

9


In [16]:
#Get the minimum value from given matrix
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
res=np.min(arr)
print(res)

1


In [18]:
#Find the number of rows and columns of a given matrix using NumPy
import numpy as np
matrix= np.arange(1,10).reshape((3, 3))
print(matrix)
print(matrix.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [19]:
#Select the elements from a given matrix
import numpy as np 
arr = np.array([9,6,2,18,4,1])  
print(arr[3])

18


In [20]:
#Find the sum of values in a matrix
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
res=np.sum(arr)
print(res)

21


In [22]:
#Calculate the sum of the diagonal elements of a NumPy array
import numpy as np
arr = np.array([[1, 2, 3],[4,5,6],[7,8,9]])
res = np.trace(arr)
print(res)

15


In [27]:
#Adding and Subtracting Matrices in Python
import numpy as np
a=np.array([[1,4],[7,5],[3,6]])
b=np.array([[7,8],[8,7],[9,0]])
print("Add: ", np.add(a,b))
print("----------------------")
print("Sub: ", np.subtract(a,b))

Add:  [[ 8 12]
 [15 12]
 [12  6]]
----------------------
Sub:  [[-6 -4]
 [-1 -2]
 [-6  6]]


In [33]:
#Ways to add row/columns in numpy array
# method 1: vstack
import numpy as np

arr = np.array([[1, 2, 3], [4,5, 7], [9, 6, 10]])
ro = np.array([1, 2, 3])
res = np.vstack ((arr, ro) )
print (res)


[[ 1  2  3]
 [ 4  5  7]
 [ 9  6 10]
 [ 1  2  3]]


In [32]:
#method 2: hstack
arr = np.array([[1, 2, 3], [4,5, 7]])
ro = np.array([[1, 2, 3],[9, 6, 10]])
res = np.hstack((arr, ro) )
print (res)

[[ 1  2  3  1  2  3]
 [ 4  5  7  9  6 10]]


In [52]:
#method 3: append()
import numpy as np
arr = np.array([[1, 2, 3],[5, 4, 3]])
row = np.array([[6, 7, 8]])
arr = np.append(arr, row, axis=0)
print(arr)

[[1 2 3]
 [5 4 3]
 [6 7 8]]


In [63]:
#method 4: insert()
import numpy as np
arr = np.array([[1, 2, 3],[4,5,7]])
row = np.array([[9, 6, 10]])
arr = np.insert(arr,2, row, axis=0)
print (arr)

[[ 1  2  3]
 [ 4  5  7]
 [ 9  6 10]]


In [36]:
#method 5: concatenate
arr = np.array([[1, 2, 3], [4,5, 7]])
ro = np.array([[1, 2, 3],[9, 6, 10]])
res = np.concatenate((arr, ro) )
print (res)

[[ 1  2  3]
 [ 4  5  7]
 [ 1  2  3]
 [ 9  6 10]]
